name: image_blur_analyzer
description: A Flutter plugin to find blurry images in the user's iOS gallery.
version: 0.0.2
homepage: https://github.com/aaidarbekov132/image_blur_analyzer.git

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# For information on the format, see https://flutter.dev/docs/development/packages-and-plugins/developing-packages.
flutter:
  # This section adds the plugin to the Flutter framework.
  plugin:
    platforms:
      ios:
        # This is the crucial line.
        # It tells Flutter that your `ImageBlurAnalyzer` class
        # is the one that contains the `register` method.
        pluginClass: ImageBlurAnalyzer
